### ISSUE TITLE
Transpiling JavaScript code fails with error (exit code: 101)

### ISSUE THREAD

**Issue by gylotip** [surma/jsxx#4]
Hello, I installed Visual Studio 2022 Community, Git and Rustup. I cloned this repo with `git clone --recursive https://github.com/surma/jsxx`, then I placed the JavaScript code `testprog.js` in that directory (that was cloned), and I ran `cat testprog.js | cargo run -- --emit-cpp`, but it gives: `error: process didn't exit successfully: \target\debug\jsxx.exe --emit-cpp\ (exit code: 101)` error. Do you know the cause of it? I originally asked it [here](https://www.reddit.com/r/AskProgramming/comments/127xh14/comment/jegtwkr/). By the way, please do not look at the previous edits, since I accidentally sent the wrong file. Here is the file: [jsxxButWithTestJSCode.zip](https://github.com/surma/jsxx/files/11130534/jsxxButWithTestJSCode.zip)

**Comment by surma** [comment]
Honestly, looking at [my code](https://github.com/surma/jsxx/blob/158786c790fc7b58bd5d947e469b6e77cc4c47ff/src/main.rs#L72-L90) I doubt this tool will run on Windows as is. You’d have to patch these sources to use `PathBuf` or something so they use the OS-native path separator.

**Comment by Samvith96** [comment]
As a way to precompile the runtime/* files, I did this

cd runtime/;
g++ --std=gnu++20 -fcoroutines -fPIC -lm *.cpp -c;
ar rcs ../jsruntime.a *.o;
cd ..;

Then to generate the cpp, I do,
cat fib_node.js |cargo run -- --emit-cpp > fib_node.cpp

and to compile I do,
g++ --std=gnu++20 -fcoroutines -fPIC -lm fib_node.cpp jsruntime.a

I am on ubuntu 22,04. @Gylotip I think your issues are related to installation and environment setup. Its very hassle-free in linux. I don't have a solution to make any open source project run on windows. As a general rule of thumb for open source projects, I follow the instructions on windows, if it doesn't work, I give up and try linux.

Hope this helps.

**Comment by Samvith96** [comment]
Also, for my version of c++ compiler, std::experimental::coroutines doesnt exist. similarly suspend_never. This gave me a lot of trouble some months back. I replaced 
s/experimental:://g
